global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    env: 'production'
    project: 'blockverse'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Node.js Backend
  - job_name: 'blockverse_api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # MongoDB Exporter
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo:9216']

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']

  # Node Exporter (host metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # NGINX Exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
